### ISSUE TITLE
download datasets in paper

### ISSUE THREAD

**Issue by genghisun** [zoie-ui/AI-Generated-Image-Detection#1]
Hello, may I ask where can I download the two generated datasets mentioned in the paper?

**Comment by Yanagi-kon** [comment]
Hello, I have the same question too! Could you please tell me where I can download these datasets?

**Comment by chenxuanseu** [comment]
Hello, I also encountered an issue with dataset loading. Could you please tell me how to obtain it? Thank you very much!

**Comment by zoie-ui** [comment]
Hello, the dataset link is avaliable in README.
