### ISSUE TITLE
About the ALASKA dataset

### ISSUE THREAD

**Issue by chenboluo** [zoie-ui/AI-Generated-Image-Detection#2]
Thank you for your excellent work, I have a question. In the paper, I see that you randomly select 20,000 uncompressed PG images of size 256 × 256 from the ALASKA database. I tried to download Uncompressed COLOR images datasets according to the readme flow, but the image format is based on TIFF. However, in the spilt file, the image format of the ALASKA dataset is all based on JPG. Am I picking the right database version?

**Comment by chenboluo** [comment]
![image](https://github.com/zoie-ui/AI-Generated-Image-Detection/assets/48652819/61c60950-07a9-4824-a3c9-1f2377f81ab4)
![image](https://github.com/zoie-ui/AI-Generated-Image-Detection/assets/48652819/a031f011-5d1c-4e74-aa39-790939b2fa30)

**Comment by zoie-ui** [comment]
Yes, “Uncompressed COLOR images datasets” is right. And in our paper, we mentioned that "To ensure uniformity, we resize all PG and T2I images to three different resolutions: 256×256, 128×128, and64 × 64. Following the resizing, we apply JPEG compression to the images using a randomly selected quality factor ranging from 75 to 95."

**Comment by chenboluo** [comment]
thank you for answer
